apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  # Tekton Pipelines: https://github.com/tektoncd/pipeline/releases/download/v0.10.0/release.yaml
  - tekton-pipelines.yaml

# Add label app=kubed to namespace
# It's needed for kind to copy the certificate [ingress-certificate] secret form cert-manager namespace)
patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: tekton-pipelines
  patch: |-
    - op: add
      path: /metadata/labels
      value:
        app: kubed
